on:
  push:
    branches: [ master, Rida, Redouane, Marlo, Zakaria ]
  pull_request:
    branches: [ master, Rida, Redouane, Marlo, Zakaria ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build maven project
      run: |
        mvn install
